[tool.poetry]
name = "stepik"
version = "0.1.0"
description = "Курсы на платформе сstepik"
authors = ["egorgavrilov <Egor4it@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
